### ISSUE TITLE
It does not support chrome.fileSystem API?

### ISSUE THREAD

**Issue by BlackGlory** [No9/chrome-fs#2]
I was pleasantly surprised that I found this project by Google today. I'm porting an old nw.js project to chrome app, I need chrome.fileSystem API to access data in local, but chrome-fs does not support chrome.fileSystem API.

I mean, chrome app developers should use chrome.fileSystem instead webkitRequestFileSystem.

Will it support chrome.fileSystem API in the future?

**Comment by No9** [comment]
Hi @BlackGlory 
Thanks for your interest in chrome-fs 

The reason I use the webkitRequestFileSystem is because my initial investigations showed that the chrome.filesystem extensions don't work outside of chrome OS. 

i.e. https://developer.chrome.com/apps/fileSystem#method-requestFileSystem 
Takes `volumeid` as one of the options 

To get the `volumeid` you need to call getvolumes
```
chrome.fileSystem.getVolumeList
```

However when I call `chrome.fileSystem.getVolumeList` on Windows Chrome App
I get
```
Unchecked runtime.lastError while running fileSystem.getVolumeList: Operation not supported on the current platform.
```

So using webkitRequestFileSystem means that we have the option of also supporting Firefox if required.

Please let me know if you feel I have missed something regarding identifying the volume. 

I would be willing to incorporate a pull for this if you have a chromebook to test it on but the default usage shouldn't require a volume parameter.

**Comment by No9** [comment]
@BlackGlory The sample app I used to prove this out 
https://gist.github.com/No9/675a86b216a05731f614

**Comment by BlackGlory** [comment]
@No9 , thank you for your reply.
As far as I know, we do not need use `chrome.fileSystem.getVolumeList` to access the local file system, as you know, it is a new API since Chrome 44.

By ·chrome.fileSystem.chooseEntry· and other API, we can also get ·entry· and ·filesystem· objects. This is a fileSystem sample provided by Chrome official, it shows how to read/write a file in chrome app, both can running in windows.
https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/filesystem-access

English is not my mother tongue, please excuse any errors on my part. :)

**Comment by No9** [comment]
Hey @BlackGlory 
OK but those calls require human interaction so don't map well into the node.js filesystem API. 

So it might make sense to use chrome-fs inside of these calls
i.e. 
`entry` object in the callback of `chrome.fileSystem.chooseEntry`  
Something like 
```
 var fs = requre('chrome-fs')

  chrome.fileSystem.chooseEntry({type: 'openFile', accepts: accepts}, function(theEntry) {
    if (!theEntry) {
      output.textContent = 'No file selected.';
      return;
    }
    fs.write(theEntry, new Buffer('hello world'), function () {
    })
  });
```

If you are looking for an full external file system representation 
There might be a way to use the directory selector to create a root for the filesystem 
```
chrome.fileSystem.chooseEntry({
      type: 'openDirectory'
```
and then persist that over app restarts using `retainEntry`
https://github.com/GoogleChrome/chrome-app-samples/blob/master/samples/filesystem-access/js/app.js#L188 

But I would need more time to understand the impact of that

**Comment by No9** [comment]
@BlackGlory Just trying out some passing the entry to the read and write calls and there a couple of funnies. Will drop a new release for it today.

**Comment by No9** [comment]
@BlackGlory so eventually I went with passing the file entry as the first parameter to open()

https://github.com/No9/chrome-fs/blob/master/test/chrome-app/index.js#L37
Is an example of how this works in Chrome App as of v10.0.0

So now if an object instead of a string is passed it will think that it is a `FileEntry` and try and use it.

**Comment by BlackGlory** [comment]
@No9  exciting update! I will try the new release later.
